<script setup>
import { ref } from 'vue';
import GameStage from './components/layout/GameStage.vue';
import ScoreCard from './components/layout/ScoreCardArea.vue';

const playerMoves = ref(0);
const totalMatches = ref(0);
const playTimer = ref(0);
const reset = ref(false);
const start = ref(true);
let intervalID;

function startTime() {
	// Delay for card loading
	setTimeout(() => {
		if (!intervalID) {
			intervalID = setInterval(() => {
				playTimer.value++;
				console.log(intervalID);
			}, 1000);
		}
	}, 2500);
}
function stopTime() {
	clearInterval(intervalID);
	intervalID = null;
}

function clearEvent() {
	playTimer.value = 0;
	playerMoves.value = 0;
	totalMatches.value = 0;
	startTime();
	reset.value = !reset.value;
}
function resetEvent() {
	stopTime();
	reset.value = !reset.value;
}

function startGame() {
	startTime();
	start.value = false;
	reset.value = true;
}
function checkMatchNum(num) {
	if (num == 12) {
		stopTime();
		return true;
	} else {
		return false;
	}
}
</script>

<template>
	<ScoreCard
		:totalMatches="totalMatches"
		:playerMoves="playerMoves"
		:playTimer="playTimer"
		:start="start"
		:reset="reset"
		@resetEmit="resetEvent"
		@beginEmit="startGame"
		@playAgainEmit="clearEvent"
	/>
	<GameStage
		v-if="reset"
		:gameOver="checkMatchNum(totalMatches)"
		:start="start"
		@updateTotalMatches="totalMatches++"
		@updatePlayerMoves="playerMoves++"
		@startOver="resetEvent"
	/>
</template>

<style>
#app {
	display: flex;
	justify-content: space-evenly;
	align-items: center;
	height: 100vh;
	background-color: #fff;
	/* Generated by: https://www.magicpattern.design/tools/css-backgrounds */
	background-image: radial-gradient(circle at center center, #459ef7, #e5e5f7),
		repeating-radial-gradient(
			circle at center center,
			#459ef7,
			#459ef7,
			4px,
			transparent 8px,
			transparent 4px
		);
	background-blend-mode: multiply;
}

/* @media in global.css  */
</style>
